const mongoose = require("mongoose");

//define a comment schema for the database
const CommentSchema = new mongoose.Schema({
  creator_name: String,
  creator_id: String,
  create_time: Date,
  parent: String, // links to the _id of a parent story (_id is an autogenerated field by Mongoose).
  content: String,
  reply_count: Number,
  last_reply_time: Date,
});

// compile model from schema
module.exports = mongoose.model("comment", CommentSchema);
